# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reviewdog < Formula
  desc "Automated code review tool integrated with any code analysis tools regardless of programming language."
  homepage "https://github.com/reviewdog/reviewdog"
  version "0.14.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.14.1/reviewdog_0.14.1_Darwin_x86_64.tar.gz"
      sha256 "634ef4b420916f9bb91a11ed4927bc378bd37462958998afa6c0551edc1b67c9"

      def install
        bin.install "reviewdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.14.1/reviewdog_0.14.1_Darwin_arm64.tar.gz"
      sha256 "b8e79b3ae4168914f9f7ed7253d74f239a27789bcaf4af02246044000f18c532"

      def install
        bin.install "reviewdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.14.1/reviewdog_0.14.1_Linux_arm64.tar.gz"
      sha256 "d387556ef1d291a360a3d2053a6de5ad856dd6c362dd0ac5793415b0c2c0aeb8"

      def install
        bin.install "reviewdog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.14.1/reviewdog_0.14.1_Linux_x86_64.tar.gz"
      sha256 "bf0ada422e13a94aafb26bcd8ade3ae6d98e6a3db4a9c1cb17686ee64e021314"

      def install
        bin.install "reviewdog"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.14.1/reviewdog_0.14.1_Linux_armv6.tar.gz"
      sha256 "11c98f16a243ef6950a1da2048964b0ecc2311fcee576f161a4cdc474d732213"

      def install
        bin.install "reviewdog"
      end
    end
  end

  test do
    system "#{bin}/reviewdog -version"
  end
end
