# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reviewdog < Formula
  desc "Automated code review tool integrated with any code analysis tools regardless of programming language."
  homepage "https://github.com/reviewdog/reviewdog"
  version "0.20.0"

  on_macos do
    on_intel do
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.20.0/reviewdog_0.20.0_Darwin_x86_64.tar.gz"
      sha256 "21dfab4181f43447b2297347e752a233184251f5659b5d7d10f387ff0ce4890a"

      def install
        bin.install "reviewdog"
      end
    end
    on_arm do
      url "https://github.com/reviewdog/reviewdog/releases/download/v0.20.0/reviewdog_0.20.0_Darwin_arm64.tar.gz"
      sha256 "d9827bd5219085e407c201b140a6622e7e0e396e524a817bc6095654631ebafa"

      def install
        bin.install "reviewdog"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reviewdog/reviewdog/releases/download/v0.20.0/reviewdog_0.20.0_Linux_x86_64.tar.gz"
        sha256 "02f60fd2fff06368fdd886ca6250fb5d6dcfaa8ae84a8e8abcd1de6d393410f5"

        def install
          bin.install "reviewdog"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/reviewdog/reviewdog/releases/download/v0.20.0/reviewdog_0.20.0_Linux_armv6.tar.gz"
        sha256 "ce29e1295001be178e511d48713b0f8a84dbfdecf040a55d0dccc2f869800c1c"

        def install
          bin.install "reviewdog"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reviewdog/reviewdog/releases/download/v0.20.0/reviewdog_0.20.0_Linux_arm64.tar.gz"
        sha256 "23a038973d38c0048106ddd3805a2e001849e46263d9f80a61a5ab070d418b31"

        def install
          bin.install "reviewdog"
        end
      end
    end
  end

  test do
    system "#{bin}/reviewdog -version"
  end
end
